---
- name: Test Openstack os_volume
  become: true
  hosts: 192.168.40.103

  tasks:
  - name: create volume 
    os_volume:
      cloud: demo_openstack
      state: present
      size: 1
      display_name: test_1
      timeout: 300
      wait: yes


