---
- name: Test Openstack os_server
  become: true
  hosts: 192.168.40.103

  tasks:
  - name: create boot volume from image
    os_volume:
      cloud: demo_openstack
      state: present
      size: 10
      display_name: test_cirros_vol_10
      image: cirros
      timeout: 300
      wait: yes


