version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - http.host=0.0.0.0
      - network.host=0.0.0.0
      - transport.host=localhost
      - bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    network_mode: host
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.0"
    hostname: "kibana"
    container_name: "kibana"
    volumes: 
      - /opt/vworld_training/elasticsearch/config/kibana.yml:/usr/share/kibana/config/kibana.yml:Z
    network_mode: host
    depends_on:
      - elasticsearch
