---
- name: Install zabbix-agent 
  become: true
  hosts: webservers

  tasks:
  - name: Install zabbix repo 
    yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
      state: present
  
  - name: Copy zabbix agent configuration
    copy: src=/opt/vworld_training/ansible/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf mode=644 
  - name: Install zabbix agent
    yum: name=zabbix-agent state=present update_cache=yes 

  - name: ensure zabbix agent started
    service: name=zabbix-agent state=started enabled=yes

  - name: Create a new host or update an existing zabbix host's info
    local_action:
      module: zabbix_host
      server_url: http://localhost
      login_user: Admin
      login_password: zabbix
      host_name: "{{ ansible_hostname }}"
      visible_name: "{{ ansible_hostname }}"
      host_groups:
        - Linux servers
      link_templates:
        - Template OS Linux
      status: enabled
      state: present
      inventory_mode: automatic
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ ip_addr }}"
          dns: ""
          port: 10050

