---
- name: Test Openstack os_volume
  become: true
  hosts: deploy

  tasks:
  - name: create 1g test volume
    os_volume:
      state: present
      cloud: vworld_test_openstack
      size: 1
      display_name: vworld_test_openstack_vol_1


 
