---
- name: Change  password
  become: true
  hosts: webservers

  tasks:
  - name: Change password of existing user
    user: name=root update_password=always password={{ new_password|password_hash('sha512') }}
